language: java
dist: trusty
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
